# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-15 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[(b'US', b'United States of America')], default=b'US', max_length=2),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
