# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-19 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drop', '0004_auto_20160908_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('percentage', models.IntegerField(default=0)),
                ('products', models.ManyToManyField(to='drop.Product')),
            ],
        ),
    ]
