# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-12 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
from lablackey.db.models import JsonMixin

class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromocodeDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32)),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('percentage', models.IntegerField(default=0)),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='First date promocode becomes active.')),
                ('end_date', models.DateField(blank=True, help_text='Optional final day this promocode can be used', null=True)),
                ('product_types', models.ManyToManyField(to='contenttypes.ContentType')),
            ],
            bases=(models.Model, JsonMixin),
        ),
    ]
