# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-30 12:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drop', '0004_cart_extra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discount', '0002_promocodediscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromocodeUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drop.Order')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.RenameModel(
            old_name='PromocodeDiscount',
            new_name='Promocode',
        ),
        migrations.AddField(
            model_name='promocodeusage',
            name='promocode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.Promocode'),
        ),
        migrations.AddField(
            model_name='promocodeusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
