# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-26 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drop', '0006_auto_20170211_2031'),
        ('discount', '0004_remove_promocodeusage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='products',
            field=models.ManyToManyField(to='drop.Product'),
        ),
    ]
