# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-09 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0005_promocode_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='product_types',
            field=models.ManyToManyField(blank=True, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='products',
            field=models.ManyToManyField(blank=True, to='drop.Product'),
        ),
    ]
