# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-03 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0007_auto_20170809_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='reuseable',
            field=models.BooleanField(default=False, help_text=b'Whether or not the same user can reuse this promocode.'),
        ),
    ]
