# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-28 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drop', '0002_category_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('order',)},
        ),
    ]
