# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-30 12:20
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('drop', '0003_auto_20161228_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='extra',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
    ]
