# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-11 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drop', '0007_auto_20161108_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(10, 'Processing'), (20, 'Confirming'), (30, 'Confirmed'), (40, 'Paid'), (50, 'Shipped'), (-10, 'Refunded')], default=10, verbose_name='Status'),
        ),
    ]
