# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-14 16:36
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('drop', '0008_auto_20170826_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='extra',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
    ]
