# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-05 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drop', '0009_auto_20161130_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpayment',
            old_name='payment_method',
            new_name='backend',
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='description',
            field=models.CharField(default='No Description given', max_length=255),
            preserve_default=False,
        ),
    ]
