# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-06 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drop', '0010_auto_20161205_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-date_added',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='backend',
            field=models.CharField(help_text='The payment backend used to process the purchase', max_length=255, verbose_name='Payment backend'),
        ),
    ]
