# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-06 21:56
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import drop.util.fields
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drop', '0011_auto_20161206_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateField(default=datetime.date.today)),
                ('delivered', models.DateTimeField(blank=True, null=True)),
                ('amount', drop.util.fields.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=30)),
                ('data', jsonfield.fields.JSONField(blank=True, default=dict, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Debit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_used', models.DateTimeField(auto_now_add=True)),
                ('amount', drop.util.fields.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=30)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftcard.Credit')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drop.Order')),
            ],
        ),
        migrations.CreateModel(
            name='GiftCardProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drop.Product')),
            ],
            bases=('drop.product',),
        ),
        migrations.AddField(
            model_name='credit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftcard.GiftCardProduct'),
        ),
        migrations.AddField(
            model_name='credit',
            name='purchased_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
