# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-30 21:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='delivery_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
