# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-19 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debit',
            name='credit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='giftcard.Credit'),
            preserve_default=False,
        ),
    ]
